services:
  backend:
    build: "./backend/"
    ports:
      - "5001:5001"
    depends_on:
      - mongo
      - puppeteer
    environment:
      - MONGODB_URI=mongodb://mongo:27017
      - NODE_OPTIONS="--max-old-space-size=8192"
    volumes:
      - ./backend/src:/code/src
      - ./backend/cache:/code/cache
      - /var/run/docker.sock:/var/run/docker.sock
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db
    command: ["--quiet", "--logpath", "/var/log/mongodb/mongod.log"]
  puppeteer:
    image: browserless/chrome
    container_name: puppeteer
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
      - CONNECTION_TIMEOUT=-1
      - DISABLE_AUTO_SET_DOWNLOAD_BEHAVIOR=true
      - ALLOW_FILE_PROTOCOL=true
  frontend:
    build: "./frontend/"
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/codeFrontend/src
      - ./frontend/public:/codeFrontend/public
