services:
  backend:
    build: "./backend/"
    ports:
      - "5001:5001"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017
    volumes:
      - ./backend/src:/code/src
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    command: ["--quiet", "--logpath", "/var/log/mongodb/mongod.log"]
  puppetter:
    image: "ghcr.io/puppeteer/puppeteer:latest"
    ports:
      - "5002:5002"
    cap_add:
      - SYS_ADMIN
    volumes:
      - /code/src
    